# Team Popcorn

---

You're a force to be reckoned with. You are team "Popcorn". Working for a big movie studio, you need to report on metrics that will help: **A)** sell movie ideas to potential investors, and **B)** maximize product placement and / or sponsorships.

**Your studios lead data scientist has given you some direction / starting points:**
 - Which movies remained in the top 10 the longest?
 - Which movies were good investments?
 - Are there any interesting trends throughout the year?
 - Google anything interesting about flagship movies in terms of partnerships and how those deals could be relevant to consider in our own research.
 
**Bonus:**
 - Do any holidays impact sales performance or position?  How could we leverage this?
 - What could we look at outside our dataset that may help project good investments?


#### End with some kind of recommendation for new partnership engagements, tied to your opening goals / metrics.

How reliable can your reocmmendation(s) be?  Back up your assumptions with facts and data.

_[There's a data dictionary available!](http://www.amstat.org/publications/jse/v17n1/datasets.mclaren.html)_

Keep in mind the main points when presenting your findings!  It's interesting to share details and sidepoints, but make sure they're supporting and relating to pitching movies to investment, and helping maximize our partnership goals.

In [1]:
import pandas as pd
import numpy as np

movies = pd.read_csv("./datasets/movie_weekend.csv")

In [21]:
movies.head(70)

,index,NUMBER,MOVIE,WEEK_NUM,WEEKEND_PER_THEATER,WEEKEND_DATE
0,0,1.0,A Beautiful Mind,1.0,701.0,12/21/01
1,1,1.0,A Beautiful Mind,2.0,14820.0,12/28/01
2,2,1.0,A Beautiful Mind,3.0,8940.0,1/4/02
3,3,1.0,A Beautiful Mind,4.0,6850.0,1/11/02
4,4,1.0,A Beautiful Mind,5.0,5280.0,1/18/02
5,5,1.0,A Beautiful Mind,6.0,5155.0,1/25/02
6,6,1.0,A Beautiful Mind,7.0,3735.0,2/1/02
7,7,1.0,A Beautiful Mind,8.0,2840.0,2/8/02
8,8,1.0,A Beautiful Mind,9.0,3890.0,2/15/02
9,9,1.0,A Beautiful Mind,10.0,2565.0,2/22/02
10,10,1.0,A Beautiful Mind,11.0,2370.0,3/1/02
11,11,1.0,A Beautiful Mind,12.0,2160.0,3/8/02
12,12,1.0,A Beautiful Mind,13.0,2205.0,3/15/02
13,13,1.0,A Beautiful Mind,14.0,2805.0,3/22/02
14,14,1.0,A Beautiful Mind,15.0,2490.0,3/29/02
15,15,1.0,A Beautiful Mind,16.0,1805.0,4/5/02
16,16,1.0,A Beautiful Mind,17.0,1325.0,4/12/02
17,17,1.0,A Beautiful Mind,18.0,1145.0,4/19/02
18,18,1.0,A Beautiful Mind,19.0,1080.0,4/26/02
19,19,1.0,A Beautiful Mind,20.0,765.0,5/3/02
20,20,1.0,A Beautiful Mind,21.0,765.0,5/10/02
21,21,1.0,A Beautiful Mind,22.0,585.0,5/17/02
22,22,1.0,A Beautiful Mind,23.0,575.0,5/24/02
23,23,2.0,American Beauty,1.0,53846.0,9/17/99
24,24,2.0,American Beauty,2.0,13838.0,9/24/99
25,25,2.0,American Beauty,3.0,11599.0,10/1/99
26,26,2.0,American Beauty,4.0,7753.0,10/8/99
27,27,2.0,American Beauty,5.0,4895.0,10/15/99
28,28,2.0,American Beauty,6.0,3551.0,10/22/99
29,29,2.0,American Beauty,7.0,2474.0,10/29/99
...,...,...,...,...,...,...
40,40,2.0,American Beauty,18.0,2168.0,1/14/00
41,41,2.0,American Beauty,19.0,1614.0,1/21/00
42,42,2.0,American Beauty,20.0,2047.0,1/28/00
43,43,2.0,American Beauty,21.0,7523.0,2/4/00
44,44,2.0,American Beauty,22.0,9185.0,2/11/00
45,45,2.0,American Beauty,23.0,5132.0,2/18/00
46,46,2.0,American Beauty,24.0,3483.0,2/25/00
47,47,2.0,American Beauty,25.0,3010.0,3/3/00
48,48,2.0,American Beauty,26.0,2408.0,3/10/00
49,49,2.0,American Beauty,27.0,1902.0,3/17/00
50,50,2.0,American Beauty,28.0,2422.0,3/24/00
51,51,2.0,American Beauty,29.0,2717.0,3/31/00
52,52,2.0,American Beauty,30.0,1731.0,4/7/00
53,53,2.0,American Beauty,31.0,1341.0,4/14/00
54,54,2.0,American Beauty,32.0,1201.0,4/21/00
55,55,2.0,American Beauty,33.0,848.0,4/28/00
56,56,2.0,American Beauty,34.0,711.0,5/5/00
57,57,2.0,American Beauty,35.0,724.0,5/12/00
58,58,2.0,American Beauty,36.0,640.0,5/19/00
59,59,2.0,American Beauty,37.0,827.0,5/26/00
60,60,2.0,American Beauty,38.0,479.0,6/2/00
61,61,3.0,Batman,1.0,18462.0,6/23/89
62,62,3.0,Batman,2.0,13664.0,6/30/89
63,63,3.0,Batman,3.0,8745.0,7/7/89
64,64,3.0,Batman,4.0,6867.0,7/14/89
65,65,3.0,Batman,5.0,5072.0,7/21/89
66,66,3.0,Batman,6.0,4068.0,7/28/89
67,67,3.0,Batman,7.0,3235.0,8/4/89
68,68,3.0,Batman,8.0,2829.0,8/11/89
69,69,3.0,Batman,9.0,2457.0,8/18/89

In [3]:
movies.dtypes

NUMBER                 float64
MOVIE                   object
WEEK_NUM               float64
WEEKEND_PER_THEATER    float64
WEEKEND_DATE            object
dtype: object

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1281 entries, 0 to 1280
Data columns (total 5 columns):
NUMBER                 1254 non-null float64
MOVIE                  1254 non-null object
WEEK_NUM               1254 non-null float64
WEEKEND_PER_THEATER    1254 non-null float64
WEEKEND_DATE           1254 non-null object
dtypes: float64(3), object(2)
memory usage: 50.1+ KB

In [5]:
movies.isnull().sum()

NUMBER                 27
MOVIE                  27
WEEK_NUM               27
WEEKEND_PER_THEATER    27
WEEKEND_DATE           27
dtype: int64

In [6]:
movies[movies.isnull()]

      NUMBER MOVIE  WEEK_NUM  WEEKEND_PER_THEATER WEEKEND_DATE
0        NaN   NaN       NaN                  NaN          NaN
1        NaN   NaN       NaN                  NaN          NaN
2        NaN   NaN       NaN                  NaN          NaN
3        NaN   NaN       NaN                  NaN          NaN
4        NaN   NaN       NaN                  NaN          NaN
5        NaN   NaN       NaN                  NaN          NaN
6        NaN   NaN       NaN                  NaN          NaN
7        NaN   NaN       NaN                  NaN          NaN
8        NaN   NaN       NaN                  NaN          NaN
9        NaN   NaN       NaN                  NaN          NaN
10       NaN   NaN       NaN                  NaN          NaN
11       NaN   NaN       NaN                  NaN          NaN
12       NaN   NaN       NaN                  NaN          NaN
13       NaN   NaN       NaN                  NaN          NaN
14       NaN   NaN       NaN                  NaN          NaN
15       NaN   NaN       NaN                  NaN          NaN
16       NaN   NaN       NaN                  NaN          NaN
17       NaN   NaN       NaN                  NaN          NaN
18       NaN   NaN       NaN                  NaN          NaN
19       NaN   NaN       NaN                  NaN          NaN
20       NaN   NaN       NaN                  NaN          NaN
21       NaN   NaN       NaN                  NaN          NaN
22       NaN   NaN       NaN                  NaN          NaN
23       NaN   NaN       NaN                  NaN          NaN
24       NaN   NaN       NaN                  NaN          NaN
25       NaN   NaN       NaN                  NaN          NaN
26       NaN   NaN       NaN                  NaN          NaN
27       NaN   NaN       NaN                  NaN          NaN
28       NaN   NaN       NaN                  NaN          NaN
29       NaN   NaN       NaN                  NaN          NaN
...      ...   ...       ...                  ...          ...
1251     NaN   NaN       NaN                  NaN          NaN
1252     NaN   NaN       NaN                  NaN          NaN
1253     NaN   NaN       NaN                  NaN          NaN
1254     NaN   NaN       NaN                  NaN          NaN
1255     NaN   NaN       NaN                  NaN          NaN
1256     NaN   NaN       NaN                  NaN          NaN
1257     NaN   NaN       NaN                  NaN          NaN
1258     NaN   NaN       NaN                  NaN          NaN
1259     NaN   NaN       NaN                  NaN          NaN
1260     NaN   NaN       NaN                  NaN          NaN
1261     NaN   NaN       NaN                  NaN          NaN
1262     NaN   NaN       NaN                  NaN          NaN
1263     NaN   NaN       NaN                  NaN          NaN
1264     NaN   NaN       NaN                  NaN          NaN
1265     NaN   NaN       NaN                  NaN          NaN
1266     NaN   NaN       NaN                  NaN          NaN
1267     NaN   NaN       NaN                  NaN          NaN
1268     NaN   NaN       NaN                  NaN          NaN
1269     NaN   NaN       NaN                  NaN          NaN
1270     NaN   NaN       NaN                  NaN          NaN
1271     NaN   NaN       NaN                  NaN          NaN
1272     NaN   NaN       NaN                  NaN          NaN
1273     NaN   NaN       NaN                  NaN          NaN
1274     NaN   NaN       NaN                  NaN          NaN
1275     NaN   NaN       NaN                  NaN          NaN
1276     NaN   NaN       NaN                  NaN          NaN
1277     NaN   NaN       NaN                  NaN          NaN
1278     NaN   NaN       NaN                  NaN          NaN
1279     NaN   NaN       NaN                  NaN          NaN
1280     NaN   NaN       NaN                  NaN          NaN

[1281 rows x 5 columns]

In [7]:
movies.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1254 entries, 0 to 1280
Data columns (total 5 columns):
NUMBER                 1254 non-null float64
MOVIE                  1254 non-null object
WEEK_NUM               1254 non-null float64
WEEKEND_PER_THEATER    1254 non-null float64
WEEKEND_DATE           1254 non-null object
dtypes: float64(3), object(2)
memory usage: 58.8+ KB

In [9]:
movies.isnull().sum()

NUMBER                 0
MOVIE                  0
WEEK_NUM               0
WEEKEND_PER_THEATER    0
WEEKEND_DATE           0
dtype: int64

In [10]:
by_movie = movies.groupby(by = 'MOVIE')[['WEEKEND_PER_THEATER']].sum()

In [11]:
by_movie

                                      WEEKEND_PER_THEATER
MOVIE
A Beautiful Mind                                  74851.0
American Beauty                                  165891.0
Batman                                            72861.0
Beverly Hills Cop                                115915.0
Chicago                                          146062.0
Crash                                             41036.0
Departed, The                                     55394.0
ET                                               201257.0
Empire Strikes Back, The                         178013.0
Forrest Gump                                     128534.0
Ghost Busters                                    113540.0
Gladiator                                         73643.0
Gods and Monsters                                 72218.0
Good Girl, The                                    75290.0
Harry Potter 1: Sorcerer's Stone                  86287.0
Harry Potter 2: Chamber of Secrets                66978.0
Harry Potter 3: Prisoner of Azkaban               62522.0
Harry Potter 4: Goblet of Fire                    71430.0
Harry Potter 5: Order of the Phoenix              51965.0
Home Alone                                       128472.0
In the Company of Men                             49422.0
Independence Day                                  71861.0
Jurassic Park                                     97520.0
Last Mimzy, The                                   13853.0
Lion King, The                                    97983.0
Lord of the Rings: Return                         73870.0
Million Dollar Baby                              154115.0
Pirates 1: Curse of the Black Pearl               72740.0
Pirates 2: Dead Man's Chest                       87171.0
Pirates 3: At World's End                         63285.0
Quinceanera                                       32472.0
Raiders of the Lost Ark                          144778.0
Return of the Jedi                               163572.0
Road Home, The                                    47026.0
Run Lola Run                                      82019.0
Shakespeare in Love                              126779.0
Shrek                                             65716.0
Shrek 2                                           77896.0
Shrek the Third                                   64396.0
Spider-Man                                        93854.0
Spider-Man 2                                      63638.0
Spider-Man 3                                      70368.0
Spider-Man 4                                        774.0
Spider-Man 5                                        604.0
Spider-Man 6                                        514.0
Spider-Man 7                                        474.0
Star Wars                                        228181.0
Star Wars: Phantom Menace                        107684.0
Super Size Me                                     55341.0
Thirteen                                          51399.0
Titanic                                          165701.0
Upside of Anger, The                              57568.0
You Can Count on Me                               93166.0

In [23]:
movies['MOVIE'].replace(['Spider-Man 4', 'Spider-Man 5','Spider-Man 6', 'Spider-Man 7'], 'Spider-Man 3', inplace = True)

In [24]:
by_movie

                                      WEEKEND_PER_THEATER
MOVIE
A Beautiful Mind                                  74851.0
American Beauty                                  165891.0
Batman                                            72861.0
Beverly Hills Cop                                115915.0
Chicago                                          146062.0
Crash                                             41036.0
Departed, The                                     55394.0
ET                                               201257.0
Empire Strikes Back, The                         178013.0
Forrest Gump                                     128534.0
Ghost Busters                                    113540.0
Gladiator                                         73643.0
Gods and Monsters                                 72218.0
Good Girl, The                                    75290.0
Harry Potter 1: Sorcerer's Stone                  86287.0
Harry Potter 2: Chamber of Secrets                66978.0
Harry Potter 3: Prisoner of Azkaban               62522.0
Harry Potter 4: Goblet of Fire                    71430.0
Harry Potter 5: Order of the Phoenix              51965.0
Home Alone                                       128472.0
In the Company of Men                             49422.0
Independence Day                                  71861.0
Jurassic Park                                     97520.0
Last Mimzy, The                                   13853.0
Lion King, The                                    97983.0
Lord of the Rings: Return                         73870.0
Million Dollar Baby                              154115.0
Pirates 1: Curse of the Black Pearl               72740.0
Pirates 2: Dead Man's Chest                       87171.0
Pirates 3: At World's End                         63285.0
Quinceanera                                       32472.0
Raiders of the Lost Ark                          144778.0
Return of the Jedi                               163572.0
Road Home, The                                    47026.0
Run Lola Run                                      82019.0
Shakespeare in Love                              126779.0
Shrek                                             65716.0
Shrek 2                                           77896.0
Shrek the Third                                   64396.0
Spider-Man                                        93854.0
Spider-Man 2                                      63638.0
Spider-Man 3                                      70368.0
Spider-Man 4                                        774.0
Spider-Man 5                                        604.0
Spider-Man 6                                        514.0
Spider-Man 7                                        474.0
Star Wars                                        228181.0
Star Wars: Phantom Menace                        107684.0
Super Size Me                                     55341.0
Thirteen                                          51399.0
Titanic                                          165701.0
Upside of Anger, The                              57568.0
You Can Count on Me                               93166.0